import { CppExercise } from "@/types";

const program = (body: string, includes = "#include <iostream>") => `${includes}

int main() {
${body}
    return 0;
}
`;

export const CPP_EXERCISES: CppExercise[] = [
  {
    number: 1,
    title: "Edad",
    description: "Lee el año de nacimiento y el año actual. Escribe la edad del usuario.",
    hints: ["Lee dos enteros con `std::cin`.", "La edad es año actual menos año de nacimiento."],
    solution: program("    int nacimiento, actual;\n    std::cin >> nacimiento >> actual;\n    std::cout << actual - nacimiento << '\\n';"),
    testCases: [{ stdin: "2000\n2024\n", expectedOutput: "24\n" }, { stdin: "1986\n2024\n", expectedOutput: "38\n" }],
  },
  {
    number: 2,
    title: "Centímetros a pulgadas",
    description: "Convierte una longitud de centímetros a pulgadas. Una pulgada equivale a 2.54 cm.",
    hints: ["Usa `double`.", "Muestra dos decimales con `std::fixed` y `std::setprecision(2)`."],
    solution: program("    double cm;\n    std::cin >> cm;\n    std::cout << std::fixed << std::setprecision(2) << cm / 2.54 << '\\n';", "#include <iostream>\n#include <iomanip>"),
    testCases: [{ stdin: "45\n", expectedOutput: "17.72\n" }, { stdin: "13\n", expectedOutput: "5.12\n" }],
  },
  {
    number: 3,
    title: "Reloj dentro de H horas",
    description: "Lee una hora en formato de 12 horas (1 a 12) y H horas. Calcula qué hora marcará el reloj.",
    hints: ["Usa el operador `%`.", "Convierte 12 a 0 antes de calcular y 0 a 12 al final."],
    solution: program("    int hora, horas;\n    std::cin >> hora >> horas;\n    hora = (hora % 12 + horas % 12) % 12;\n    std::cout << (hora == 0 ? 12 : hora) << '\\n';"),
    testCases: [{ stdin: "3\n5\n", expectedOutput: "8\n" }, { stdin: "11\n43\n", expectedOutput: "6\n" }],
  },
  {
    number: 4,
    title: "Media de cuatro valores",
    description: "Lee cuatro valores reales y escribe su media aritmética.",
    hints: ["Usa `double`.", "Divide entre `4.0` para conservar decimales."],
    solution: program("    double a, b, c, d;\n    std::cin >> a >> b >> c >> d;\n    std::cout << (a + b + c + d) / 4.0 << '\\n';"),
    testCases: [{ stdin: "55\n71\n46\n87\n", expectedOutput: "64.75\n" }],
  },
  {
    number: 5,
    title: "Círculo",
    description: "Lee el radio de un círculo y escribe primero su perímetro y después su área.",
    hints: ["Usa π = 3.14.", "Perímetro = 2πr; área = πr²."],
    solution: program("    double r;\n    constexpr double pi = 3.14;\n    std::cin >> r;\n    std::cout << 2 * pi * r << '\\n' << pi * r * r << '\\n';"),
    testCases: [{ stdin: "5\n", expectedOutput: "31.4\n78.5\n" }],
  },
  {
    number: 6,
    title: "Hipotenusa",
    description: "Lee los dos catetos de un triángulo rectángulo. Escribe la hipotenusa con dos decimales.",
    hints: ["Incluye `<cmath>`.", "Usa `std::sqrt(a * a + b * b)`."],
    solution: program("    double a, b;\n    std::cin >> a >> b;\n    std::cout << std::fixed << std::setprecision(2) << std::sqrt(a * a + b * b) << '\\n';", "#include <iostream>\n#include <iomanip>\n#include <cmath>"),
    testCases: [{ stdin: "7\n5\n", expectedOutput: "8.60\n" }, { stdin: "3\n4\n", expectedOutput: "5.00\n" }],
  },
  {
    number: 7,
    title: "Número de dígitos",
    description: "Lee un entero positivo N y calcula su número de dígitos con ⌊log10(N) + 1⌋.",
    hints: ["Necesitas `<cmath>`.", "Convierte el resultado a entero después de aplicar `std::floor`."],
    solution: program("    long long n;\n    std::cin >> n;\n    std::cout << static_cast<int>(std::floor(std::log10(n) + 1)) << '\\n';", "#include <iostream>\n#include <cmath>"),
    testCases: [{ stdin: "999\n", expectedOutput: "3\n" }, { stdin: "10000\n", expectedOutput: "5\n" }],
  },
  {
    number: 8,
    title: "Polinomio de segundo grado",
    description: "Lee a, b, c y x. Calcula f(x) = ax² + bx + c.",
    hints: ["Usa `double`.", "Puedes escribir `a * x * x` directamente."],
    solution: program("    double a, b, c, x;\n    std::cin >> a >> b >> c >> x;\n    std::cout << a * x * x + b * x + c << '\\n';"),
    testCases: [{ stdin: "2\n3.7\n-0.5\n100\n", expectedOutput: "20369.5\n" }, { stdin: "1\n0\n-4\n3\n", expectedOutput: "5\n" }],
  },
  {
    number: 9,
    title: "Raíces cuadráticas",
    description: "Lee a, b y c. Calcula las raíces reales de ax² + bx + c = 0. Si no existen, escribe `SIN_RAICES_REALES`. Muestra las raíces ordenadas de menor a mayor con dos decimales.",
    hints: ["El discriminante es b² - 4ac.", "Si vale cero, solo existe una raíz real."],
    solution: program("    double a, b, c;\n    std::cin >> a >> b >> c;\n    double d = b * b - 4 * a * c;\n    if (d < 0) {\n        std::cout << \"SIN_RAICES_REALES\\n\";\n    } else {\n        double x1 = (-b - std::sqrt(d)) / (2 * a);\n        double x2 = (-b + std::sqrt(d)) / (2 * a);\n        std::cout << std::fixed << std::setprecision(2) << x1;\n        if (d > 0) std::cout << ' ' << x2;\n        std::cout << '\\n';\n    }", "#include <iostream>\n#include <iomanip>\n#include <cmath>"),
    testCases: [{ label: "Dos raíces", stdin: "1\n-5\n6\n", expectedOutput: "2.00 3.00\n" }, { label: "Raíz doble", stdin: "1\n-2\n1\n", expectedOutput: "1.00\n" }, { label: "Sin raíces reales", stdin: "1\n0\n1\n", expectedOutput: "SIN_RAICES_REALES\n" }],
  },
  {
    number: 10,
    title: "Área de Herón",
    description: "Lee tres lados válidos de un triángulo y calcula su área usando la fórmula de Herón. Muestra dos decimales.",
    hints: ["s = (a + b + c) / 2.", "El área es la raíz de s(s-a)(s-b)(s-c)."],
    solution: program("    double a, b, c;\n    std::cin >> a >> b >> c;\n    double s = (a + b + c) / 2;\n    std::cout << std::fixed << std::setprecision(2)\n              << std::sqrt(s * (s - a) * (s - b) * (s - c)) << '\\n';", "#include <iostream>\n#include <iomanip>\n#include <cmath>"),
    testCases: [{ stdin: "3\n4\n5\n", expectedOutput: "6.00\n" }],
  },
  {
    number: 11,
    title: "Identidad trigonométrica",
    description: "Lee α en radianes y escribe sin²(α) + cos²(α) con seis decimales.",
    hints: ["Incluye `<cmath>`.", "Multiplica cada valor por sí mismo."],
    solution: program("    double alfa;\n    std::cin >> alfa;\n    std::cout << std::fixed << std::setprecision(6)\n              << std::sin(alfa) * std::sin(alfa) + std::cos(alfa) * std::cos(alfa) << '\\n';", "#include <iostream>\n#include <iomanip>\n#include <cmath>"),
    testCases: [{ stdin: "0\n", expectedOutput: "1.000000\n" }, { stdin: "1.57\n", expectedOutput: "1.000000\n" }],
  },
  {
    number: 12,
    title: "Par o impar",
    description: "Lee un entero. Escribe `PAR` si es par; en otro caso, `IMPAR`.",
    hints: ["Usa el resto de dividir entre 2.", "`n % 2 == 0` también funciona con enteros negativos."],
    solution: program("    long long n;\n    std::cin >> n;\n    std::cout << (n % 2 == 0 ? \"PAR\" : \"IMPAR\") << '\\n';"),
    testCases: [{ stdin: "4\n", expectedOutput: "PAR\n" }, { stdin: "3\n", expectedOutput: "IMPAR\n" }],
  },
  {
    number: 13,
    title: "Tipo de triángulo",
    description: "Lee tres lados. Escribe `INVALIDO` si no forman un triángulo; si lo forman, `EQUILATERO`, `ISOSCELES` o `ESCALENO`.",
    hints: ["Comprueba que cada lado sea menor que la suma de los otros dos.", "Comprueba primero si todos los lados son iguales."],
    solution: program("    double a, b, c;\n    std::cin >> a >> b >> c;\n    if (a <= 0 || b <= 0 || c <= 0 || a + b <= c || a + c <= b || b + c <= a) {\n        std::cout << \"INVALIDO\\n\";\n    } else if (a == b && b == c) {\n        std::cout << \"EQUILATERO\\n\";\n    } else if (a == b || a == c || b == c) {\n        std::cout << \"ISOSCELES\\n\";\n    } else {\n        std::cout << \"ESCALENO\\n\";\n    }"),
    testCases: [{ label: "Inválido", stdin: "4\n6\n1\n", expectedOutput: "INVALIDO\n" }, { label: "Equilátero", stdin: "37\n37\n37\n", expectedOutput: "EQUILATERO\n" }, { label: "Isósceles", stdin: "1\n2\n2\n", expectedOutput: "ISOSCELES\n" }, { label: "Escaleno", stdin: "3\n5\n4\n", expectedOutput: "ESCALENO\n" }],
  },
  {
    number: 14,
    title: "Potencias de 2",
    description: "Lee un exponente N no negativo. Escribe las potencias de 2 desde 2⁰ hasta 2ᴺ, separadas por espacios.",
    hints: ["Empieza con 1.", "Después de imprimir, multiplica el valor por 2."],
    solution: program("    int n;\n    std::cin >> n;\n    long long potencia = 1;\n    for (int i = 0; i <= n; ++i) {\n        if (i) std::cout << ' ';\n        std::cout << potencia;\n        potencia *= 2;\n    }\n    std::cout << '\\n';"),
    testCases: [{ stdin: "10\n", expectedOutput: "1 2 4 8 16 32 64 128 256 512 1024\n" }, { stdin: "0\n", expectedOutput: "1\n" }],
  },
  {
    number: 15,
    title: "Divisores",
    description: "Lee un entero positivo N y escribe todos sus divisores positivos, ordenados y separados por espacios.",
    hints: ["Un divisor deja resto 0.", "Recorre desde 1 hasta N."],
    solution: program("    long long n;\n    std::cin >> n;\n    bool primero = true;\n    for (long long i = 1; i <= n; ++i) {\n        if (n % i == 0) {\n            if (!primero) std::cout << ' ';\n            std::cout << i;\n            primero = false;\n        }\n    }\n    std::cout << '\\n';"),
    testCases: [{ stdin: "10\n", expectedOutput: "1 2 5 10\n" }, { stdin: "13\n", expectedOutput: "1 13\n" }],
  },
  {
    number: 16,
    title: "Fibonacci",
    description: "Lee N y escribe los N primeros términos de Fibonacci, empezando por 0, separados por espacios.",
    hints: ["Los dos primeros términos son 0 y 1.", "Guarda los dos términos anteriores."],
    solution: program("    int n;\n    std::cin >> n;\n    long long a = 0, b = 1;\n    for (int i = 0; i < n; ++i) {\n        if (i) std::cout << ' ';\n        std::cout << a;\n        long long siguiente = a + b;\n        a = b;\n        b = siguiente;\n    }\n    std::cout << '\\n';"),
    testCases: [{ stdin: "10\n", expectedOutput: "0 1 1 2 3 5 8 13 21 34\n" }, { stdin: "1\n", expectedOutput: "0\n" }],
  },
  {
    number: 17,
    title: "Invertir tres dígitos",
    description: "Lee un entero positivo de tres dígitos y escribe sus dígitos en orden inverso.",
    hints: ["Usa `% 10` para obtener el último dígito.", "Usa `/ 10` para eliminarlo."],
    solution: program("    int n;\n    std::cin >> n;\n    int centenas = n / 100;\n    int decenas = n / 10 % 10;\n    int unidades = n % 10;\n    std::cout << unidades * 100 + decenas * 10 + centenas << '\\n';"),
    testCases: [{ stdin: "345\n", expectedOutput: "543\n" }, { stdin: "241\n", expectedOutput: "142\n" }],
  },
  {
    number: 18,
    title: "Tiempo a segundos",
    description: "Lee años, días, horas, minutos y segundos. Calcula el total de segundos, considerando años de 365 días.",
    hints: ["Usa `long long`.", "Acumula desde las unidades más grandes."],
    solution: program("    long long anios, dias, horas, minutos, segundos;\n    std::cin >> anios >> dias >> horas >> minutos >> segundos;\n    std::cout << (((anios * 365 + dias) * 24 + horas) * 60 + minutos) * 60 + segundos << '\\n';"),
    testCases: [{ stdin: "20 4 200 50 1234\n", expectedOutput: "631789834\n" }, { stdin: "0 0 1 1 1\n", expectedOutput: "3661\n" }],
  },
  {
    number: 19,
    title: "Segundos a tiempo",
    description: "Lee una cantidad de segundos. Escribe años, días, horas, minutos y segundos: cinco enteros separados por espacios.",
    hints: ["Extrae primero los años con división entera.", "Actualiza el resto con `%`."],
    solution: program("    long long total;\n    std::cin >> total;\n    long long anios = total / (365LL * 24 * 60 * 60);\n    total %= 365LL * 24 * 60 * 60;\n    long long dias = total / (24 * 60 * 60);\n    total %= 24 * 60 * 60;\n    long long horas = total / 3600;\n    total %= 3600;\n    long long minutos = total / 60;\n    long long segundos = total % 60;\n    std::cout << anios << ' ' << dias << ' ' << horas << ' ' << minutos << ' ' << segundos << '\\n';"),
    testCases: [{ stdin: "1000000000\n", expectedOutput: "31 259 1 46 40\n" }, { stdin: "3661\n", expectedOutput: "0 0 1 1 1\n" }],
  },
  {
    number: 20,
    title: "Producto grande",
    description: "Lee dos números naturales y escribe su producto. Usa un tipo que soporte productos grandes sin bibliotecas externas.",
    hints: ["`unsigned long long` admite valores mayores que `int` y `long long` positivos.", "Lee ambos operandos con el mismo tipo."],
    solution: program("    unsigned long long a, b;\n    std::cin >> a >> b;\n    std::cout << a * b << '\\n';"),
    testCases: [{ stdin: "4000000000 3000000000\n", expectedOutput: "12000000000000000000\n" }, { stdin: "123456789 987654321\n", expectedOutput: "121932631112635269\n" }],
  },
  {
    number: 21,
    title: "Sumatorio iterativo",
    description: "Lee N y calcula la suma de los naturales desde 1 hasta N mediante un bucle.",
    hints: ["Inicializa el acumulador a 0.", "Recorre de 1 hasta N, incluido."],
    solution: program("    long long n, suma = 0;\n    std::cin >> n;\n    for (long long i = 1; i <= n; ++i) suma += i;\n    std::cout << suma << '\\n';"),
    testCases: [{ stdin: "10\n", expectedOutput: "55\n" }, { stdin: "1\n", expectedOutput: "1\n" }],
  },
  {
    number: 22,
    title: "Sumatorio de Gauss",
    description: "Lee N y calcula la suma de 1 a N con S = N × (N + 1) / 2.",
    hints: ["Usa `long long`.", "No necesitas ningún bucle."],
    solution: program("    long long n;\n    std::cin >> n;\n    std::cout << n * (n + 1) / 2 << '\\n';"),
    testCases: [{ stdin: "10\n", expectedOutput: "55\n" }, { stdin: "1000000\n", expectedOutput: "500000500000\n" }],
  },
  {
    number: 23,
    title: "Múltiplos de 3 o 5",
    description: "Escribe la suma de todos los múltiplos de 3 o 5 menores que 1000.",
    hints: ["Recorre de 1 a 999.", "Evita sumar dos veces un múltiplo de 15."],
    solution: program("    int suma = 0;\n    for (int i = 1; i < 1000; ++i) {\n        if (i % 3 == 0 || i % 5 == 0) suma += i;\n    }\n    std::cout << suma << '\\n';"),
    testCases: [{ stdin: "", expectedOutput: "233168\n" }],
  },
  {
    number: 24,
    title: "Fibonacci par",
    description: "Escribe la suma de los términos pares de Fibonacci menores que 1000.",
    hints: ["Genera Fibonacci hasta llegar a 1000.", "Suma solo los términos cuyo resto entre 2 sea cero."],
    solution: program("    int a = 0, b = 1, suma = 0;\n    while (a < 1000) {\n        if (a % 2 == 0) suma += a;\n        int siguiente = a + b;\n        a = b;\n        b = siguiente;\n    }\n    std::cout << suma << '\\n';"),
    testCases: [{ stdin: "", expectedOutput: "798\n" }],
  },
  {
    number: 25,
    title: "Secuencia de Collatz",
    description: "Lee n positivo y escribe su secuencia de Collatz hasta 1, separada por espacios.",
    hints: ["Si n es par, divídelo entre 2.", "Si es impar, usa 3n + 1."],
    solution: program("    unsigned long long n;\n    std::cin >> n;\n    while (true) {\n        std::cout << n;\n        if (n == 1) break;\n        std::cout << ' ';\n        n = n % 2 == 0 ? n / 2 : 3 * n + 1;\n    }\n    std::cout << '\\n';"),
    testCases: [{ stdin: "18\n", expectedOutput: "18 9 28 14 7 22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1\n" }, { stdin: "20\n", expectedOutput: "20 10 5 16 8 4 2 1\n" }],
  },
  {
    number: 26,
    title: "Terna pitagórica",
    description: "Lee tres enteros positivos ordenados a ≤ b ≤ c. Escribe `SI` si forman una terna pitagórica; si no, `NO`.",
    hints: ["Comprueba a² + b² == c².", "Usa `long long` para el cálculo."],
    solution: program("    long long a, b, c;\n    std::cin >> a >> b >> c;\n    std::cout << (a * a + b * b == c * c ? \"SI\" : \"NO\") << '\\n';"),
    testCases: [{ stdin: "6 8 10\n", expectedOutput: "SI\n" }, { stdin: "4 6 19\n", expectedOutput: "NO\n" }],
  },
  {
    number: 27,
    title: "Triángulos rectángulos enteros",
    description: "Lee N. Para cada a desde 3 hasta N, escribe `a b c` si las fórmulas dadas generan un TRE.",
    hints: ["Para a impar, k = (a - 1) / 2.", "Para a par, k = a / 2. El primer resultado es 3 4 5."],
    solution: program("    int n;\n    std::cin >> n;\n    for (int a = 3; a <= n; ++a) {\n        long long k, b, c;\n        if (a % 2) {\n            k = (a - 1) / 2;\n            b = 2 * k * (k + 1);\n            c = b + 1;\n        } else {\n            k = a / 2;\n            b = k * k - 1;\n            c = k * k + 1;\n        }\n        std::cout << a << ' ' << b << ' ' << c << '\\n';\n    }"),
    testCases: [{ stdin: "5\n", expectedOutput: "3 4 5\n4 3 5\n5 12 13\n" }, { stdin: "3\n", expectedOutput: "3 4 5\n" }],
  },
  {
    number: 28,
    title: "Dígito mayor y menor",
    description: "Lee un número natural y escribe primero su dígito menor y después su dígito mayor.",
    hints: ["Extrae cada dígito con `% 10`.", "Inicializa mínimo en 9 y máximo en 0."],
    solution: program("    unsigned long long n;\n    std::cin >> n;\n    int minimo = 9, maximo = 0;\n    do {\n        int digito = n % 10;\n        if (digito < minimo) minimo = digito;\n        if (digito > maximo) maximo = digito;\n        n /= 10;\n    } while (n > 0);\n    std::cout << minimo << ' ' << maximo << '\\n';"),
    testCases: [{ stdin: "5\n", expectedOutput: "5 5\n" }, { stdin: "2025\n", expectedOutput: "0 5\n" }],
  },
];
